// Generated by https://quicktype.io

import { BlocksContent } from "@strapi/blocks-react-renderer";
import { ReactNode } from "react";

export interface Response {
  data: Data;
  meta: Meta;
}

export interface Data {
  id: number;
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date;
  locale: string;
  homeSections: HomePage[];
}

export interface HomePage {
  hero: HeroSection;
  featured: FeaturedSection;
  features: FeaturesSection;
  amenities: AmenitiesSection;
  contact: ContactSection;
  "c2-a": C2ASection;
}

export interface HeroSection {
  title: BlocksContent;
  description: BlocksContent;
  primaryBtn: Button;
  secondaryBtn: Button;
  cover: Cover;
}

export interface Button {
  id: number;
  text: string;
}

export interface Description {
  type: string;
  children: DescriptionChild[];
}

export interface DescriptionChild {
  type: string;
  text: string;
}

export interface Heading {
  id: number;
  title: string;
  description: null | string;
}

export interface Property {
  id: number;
  documentId: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date;
  locale: string;
  name: string;
  description: string;
  available: boolean;
  slug: string;
  rooms: number;
  bathrooms: number;
  guests: number;
  name_location: null;
  area: number | null;
  maps_location: null;
  featured: boolean;
}

export interface Title {
  type: string;
  children: TitleChild[];
}

export interface TitleChild {
  text: string;
  type: string;
  bold?: boolean;
}

export interface Meta {}

export interface Cover {
  id: number;
  documentId: string;
  name: string;
  alternativeText: null | string;
  caption: null | string;
  width: number;
  height: number;
  formats: any;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: null;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date;
}

export interface FeaturedSection {
  id: number;
  heading: Heading;
  property: Property[];
}

export interface FeaturesSection {
  id: number;
  heading: Heading;
  features: any[];
}

export interface AmenitiesSection {
  id: number;
  heading: Heading;
  amenities: Amenities[];
}

export interface Amenities {
  id: number;
  name: string;
}

export interface ContactSection {
  id: number;
  email: string;
  phone: string;
  direction: string;
  heading: Heading;
}

export interface C2ASection {
  id: number;
  heading: Heading;
  button: Button;
}
